import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@contexts/UserAuthContext";
import { Layout } from "antd";
import Sider from "antd/es/layout/Sider";
import { Header, Content } from "antd/es/layout/layout";
import SideBar from "@components/SideBar";
import PathProvider from "@contexts/PathContext";
import HeaderBar from "@components/HeaderBar";
import AntdConfigProvider from "../provider/AntdConfigProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Revomed - CRM",
  description: "Generated by Cy-Click",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ fontFamily: "LINESeedSans", minHeight: "100vh" }}
      >
        <ContextProvider>
          <AntdConfigProvider>
            <PathProvider>
              <Layout style={{ minHeight: "100vh" }}>
                <SideBar />
                <Layout>
                  <HeaderBar />
                  <Content>{children}</Content>
                </Layout>
              </Layout>
            </PathProvider>
          </AntdConfigProvider>
        </ContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
