import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@contexts/UserAuthContext";
import { Layout } from "antd";
import Sider from "antd/es/layout/Sider";
import { Header, Content } from "antd/es/layout/layout";
import SideBar from "@components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Revomed - CRM",
  description: "Generated by Cy-Click",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ fontFamily: "LINESeedSans", minHeight: "100vh" }}
      >
        <ContextProvider>
          <Layout style={{ minHeight : '100vh'}}>
            <SideBar />
            <Layout>
              <Header>Header1234</Header>
              <Content>{children}</Content>
            </Layout>
          </Layout>
        </ContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
